### ISSUE TITLE
GCNConv example fails

### ISSUE THREAD

**Issue by avik-pal** [yuehhua/GeometricFlux.jl#61]
I tried to run the gcn example. But it seems to fail on both CPU and GPU (with different errors)

<details><summary>Error on GPU</summary>
<p>

```julia
type CuArray has no field f

Stacktrace:
 [1] getproperty(::CuArray{Bool,2,Nothing}, ::Symbol) at ./Base.jl:33
 [2] adjoint at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:204 [inlined]
 [3] _pullback(::Zygote.Context, ::typeof(ZygoteRules.literal_getproperty), ::CuArray{Bool,2,Nothing}, ::Val{:f}) at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47
 [4] #_mapreduce#27 at /home/avik-pal/.julia/packages/GPUArrays/JqOUg/src/host/mapreduce.jl:49 [inlined]
 [5] _pullback(::Zygote.Context, ::GPUArrays.var"##_mapreduce#27", ::Colon, ::Nothing, ::typeof(GPUArrays._mapreduce), ::typeof(==), ::typeof(&), ::CuArray{Float32,2,Nothing}, ::LinearAlgebra.Adjoint{Float32,CuArray{Float32,2,Nothing}}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [6] adjoint at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:179 [inlined]
 [7] _pullback at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47 [inlined]
 [8] _pullback(::Zygote.Context, ::GPUArrays.var"#_mapreduce##kw", ::NamedTuple{(:dims, :init),Tuple{Colon,Nothing}}, ::typeof(GPUArrays._mapreduce), ::typeof(==), ::typeof(&), ::CuArray{Float32,2,Nothing}, ::LinearAlgebra.Adjoint{Float32,CuArray{Float32,2,Nothing}}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [9] adjoint at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:179 [inlined]
 [10] _pullback at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47 [inlined]
 [11] #mapreduce#25 at /home/avik-pal/.julia/packages/GPUArrays/JqOUg/src/host/mapreduce.jl:28 [inlined]
 [12] adjoint at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:179 [inlined]
 [13] _pullback at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47 [inlined]
 [14] mapreduce at /home/avik-pal/.julia/packages/GPUArrays/JqOUg/src/host/mapreduce.jl:28 [inlined]
 [15] ishermitian at /home/avik-pal/.julia/packages/GPUArrays/JqOUg/src/host/mapreduce.jl:86 [inlined]
 [16] issymmetric at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/generic.jl:1157 [inlined]
 [17] #degrees#73 at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/operations/linalg.jl:35 [inlined]
 [18] _pullback(::Zygote.Context, ::GeometricFlux.var"##degrees#73", ::Symbol, ::typeof(GeometricFlux.degrees), ::CuArray{Float32,2,Nothing}, ::Type{Float32}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0 (repeats 2 times)
 [19] #inv_sqrt_degree_matrix#75 at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/operations/linalg.jl:92 [inlined]
 [20] _pullback(::Zygote.Context, ::GeometricFlux.var"##inv_sqrt_degree_matrix#75", ::Symbol, ::typeof(GeometricFlux.inv_sqrt_degree_matrix), ::CuArray{Float32,2,Nothing}, ::Type{Float32}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0 (repeats 2 times)
 [21] #normalized_laplacian#77 at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/operations/linalg.jl:122 [inlined]
 [22] _pullback(::Zygote.Context, ::GeometricFlux.var"##normalized_laplacian#77", ::Bool, ::typeof(normalized_laplacian), ::CuArray{Float32,2,Nothing}, ::Type{Float32}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0 (repeats 2 times)
 [23] #normalized_laplacian#85 at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/graph/featuredgraphs.jl:68 [inlined]
 [24] _pullback(::Zygote.Context, ::GeometricFlux.var"##normalized_laplacian#85", ::Bool, ::typeof(normalized_laplacian), ::FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}, ::Type{Float32}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0 (repeats 2 times)
 [25] GCNConv at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/layers/conv.jl:48 [inlined]
 [26] _pullback(::Zygote.Context, ::GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}}, ::CuArray{Float32,2,Nothing}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [27] applychain at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/layers/basic.jl:36 [inlined]
 [28] _pullback(::Zygote.Context, ::typeof(Flux.applychain), ::Tuple{GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},Dropout{Float64,Colon},GCNConv{Float32,typeof(identity),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},typeof(softmax)}, ::CuArray{Float32,2,Nothing}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [29] Chain at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/layers/basic.jl:38 [inlined]
 [30] _pullback(::Zygote.Context, ::Chain{Tuple{GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},Dropout{Float64,Colon},GCNConv{Float32,typeof(identity),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},typeof(softmax)}}, ::CuArray{Float32,2,Nothing}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [31] loss at ./In[4]:20 [inlined]
 [32] _pullback(::Zygote.Context, ::typeof(loss), ::CuArray{Float32,2,Nothing}, ::CuArray{Float32,2,Nothing}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [33] adjoint at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:179 [inlined]
 [34] _pullback at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47 [inlined]
 [35] #17 at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:89 [inlined]
 [36] _pullback(::Zygote.Context, ::Flux.Optimise.var"#17#25"{typeof(loss),Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,2,Nothing}}}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [37] pullback(::Function, ::Zygote.Params) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface.jl:174
 [38] gradient(::Function, ::Zygote.Params) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface.jl:54
 [39] macro expansion at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:88 [inlined]
 [40] macro expansion at /home/avik-pal/.julia/packages/Juno/tLMZd/src/progress.jl:134 [inlined]
 [41] train!(::typeof(loss), ::Zygote.Params, ::Array{Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,2,Nothing}},1}, ::ADAM; cb::Flux.var"#throttled#20"{Flux.var"#throttled#16#21"{Bool,Bool,typeof(evalcb),Int64}}) at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:81
 [42] top-level scope at ./In[4]:30
```

</p>
</details>

<details><summary>Error on CPU</summary>
<p>

```julia
Need an adjoint for constructor SparseMatrixCSC{Float32,Int64}. Gradient is of type Array{Float32,2}

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::Zygote.Jnew{SparseMatrixCSC{Float32,Int64},Nothing,false})(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:306
 [3] (::Zygote.var"#392#back#193"{Zygote.Jnew{SparseMatrixCSC{Float32,Int64},Nothing,false}})(::Array{Float32,2}) at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [4] SparseMatrixCSC at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SparseArrays/src/sparsematrix.jl:32 [inlined]
 [5] (::typeof(∂(SparseMatrixCSC{Float32,Int64})))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [6] SparseMatrixCSC at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SparseArrays/src/sparsematrix.jl:45 [inlined]
 [7] (::typeof(∂(SparseMatrixCSC)))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [8] SparseMatrixCSC at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SparseArrays/src/sparsematrix.jl:580 [inlined]
 [9] (::typeof(∂(SparseMatrixCSC{Float32,Int64})))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [10] convert at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SparseArrays/src/sparsematrix.jl:603 [inlined]
 [11] (::typeof(∂(convert)))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [12] GCNConv at /home/avik-pal/.julia/packages/GeometricFlux/0yTVp/src/layers/conv.jl:49 [inlined]
 [13] (::typeof(∂(λ)))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [14] applychain at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/layers/basic.jl:36 [inlined]
 [15] (::typeof(∂(applychain)))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [16] Chain at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/layers/basic.jl:38 [inlined]
 [17] (::typeof(∂(λ)))(::Array{Float32,2}) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [18] loss at ./In[5]:20 [inlined]
 [19] (::typeof(∂(loss)))(::Float32) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [20] #174 at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/lib/lib.jl:182 [inlined]
 [21] #358#back at /home/avik-pal/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49 [inlined]
 [22] #17 at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:89 [inlined]
 [23] (::typeof(∂(λ)))(::Float32) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface2.jl:0
 [24] (::Zygote.var"#49#50"{Zygote.Params,Zygote.Context,typeof(∂(λ))})(::Float32) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface.jl:179
 [25] gradient(::Function, ::Zygote.Params) at /home/avik-pal/.julia/packages/Zygote/YeCEW/src/compiler/interface.jl:55
 [26] macro expansion at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:88 [inlined]
 [27] macro expansion at /home/avik-pal/.julia/packages/Juno/tLMZd/src/progress.jl:134 [inlined]
 [28] train!(::typeof(loss), ::Zygote.Params, ::Array{Tuple{SparseMatrixCSC{Float32,Int64},SparseMatrixCSC{Float32,Int64}},1}, ::ADAM; cb::Flux.var"#throttled#20"{Flux.var"#throttled#16#21"{Bool,Bool,typeof(evalcb),Int64}}) at /home/avik-pal/.julia/packages/Flux/Fj3bt/src/optimise/train.jl:81
 [29] top-level scope at ./In[5]:30
```

</p>
</details>

**Comment by ilancoulon** [comment]
I indeed have the same error.

Using the master version (not released yet), I have another one though:
```
ERROR: LoadError: MethodError: no method matching Float32(::ForwardDiff.Dual{Nothing,Float32,1})
Closest candidates are:
  Float32(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  Float32(::T) where T<:Number at boot.jl:715
  Float32(::Int8) at float.jl:60
  ...
Stacktrace:
 [1] (::CuArrays.var"#68#69"{Float32})(::ForwardDiff.Dual{Nothing,Float32,1}) at C:\Users\ilanc\.julia\packages\CuArrays\YFdj7\src\broadcast.jl:21
 [2] (::Zygote.var"#1161#1164"{CuArrays.var"#68#69"{Float32}})(::Float32) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\lib\broadcast.jl:175
 [3] _broadcast_getindex_evalf at .\broadcast.jl:631 [inlined]
 [4] _broadcast_getindex at .\broadcast.jl:604 [inlined]
 [5] getindex at .\broadcast.jl:564 [inlined]
 [6] copy at .\broadcast.jl:854 [inlined]
 [7] materialize(::Base.Broadcast.Broadcasted{CuArrays.CuArrayStyle{2},Nothing,Zygote.var"#1161#1164"{CuArrays.var"#68#69"{Float32}},Tuple{CuArray{Float32,2,Nothing}}}) at .\broadcast.jl:820
 [8] broadcast_forward(::Function, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\lib\broadcast.jl:181
 [9] adjoint at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\lib\broadcast.jl:197 [inlined]
 [10] _pullback at C:\Users\ilanc\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:47 [inlined]
 [11] adjoint at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\lib\lib.jl:179 [inlined]
 [12] _pullback at C:\Users\ilanc\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:47 [inlined]
 [13] broadcasted at .\broadcast.jl:1232 [inlined]
 [14] _pullback(::Zygote.Context, ::typeof(Base.Broadcast.broadcasted), ::Type{Float32}, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [15] #normalized_laplacian#79 at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\src\operations\linalg.jl:124 [inlined]
 [16] _pullback(::Zygote.Context, ::GeometricFlux.var"##normalized_laplacian#79", ::Bool, ::typeof(normalized_laplacian), ::CuArray{Float32,2,Nothing}, ::Type{Float32}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0 (repeats 2 times)
 [17] #normalized_laplacian#87 at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\src\graph\featuredgraphs.jl:68 [inlined]
 [18] _pullback(::Zygote.Context, ::GeometricFlux.var"##normalized_laplacian#87", ::Bool, ::typeof(normalized_laplacian), ::FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}, ::Type{Float32}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0 (repeats 2 times)
 [19] GCNConv at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\src\layers\conv.jl:48 [inlined]
 [20] _pullback(::Zygote.Context, ::GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}}, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [21] applychain at C:\Users\ilanc\.julia\packages\Flux\Fj3bt\src\layers\basic.jl:36 [inlined]
 [22] _pullback(::Zygote.Context, ::typeof(Flux.applychain), ::Tuple{GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},Dropout{Float64,Colon},GCNConv{Float32,typeof(identity),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},typeof(softmax)}, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [23] Chain at C:\Users\ilanc\.julia\packages\Flux\Fj3bt\src\layers\basic.jl:38 [inlined]
 [24] _pullback(::Zygote.Context, ::Chain{Tuple{GCNConv{Float32,typeof(relu),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},Dropout{Float64,Colon},GCNConv{Float32,typeof(identity),FeaturedGraph{CuArray{Float32,2,Nothing},Nothing}},typeof(softmax)}}, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [25] loss at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\examples\gcn.jl:34 [inlined]
 [26] _pullback(::Zygote.Context, ::typeof(loss), ::CuArray{Float32,2,Nothing}, ::CuArray{Float32,2,Nothing}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [27] adjoint at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\lib\lib.jl:179 [inlined]
 [28] _pullback at C:\Users\ilanc\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:47 [inlined]
 [29] #17 at C:\Users\ilanc\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:89 [inlined]
 [30] _pullback(::Zygote.Context, ::Flux.Optimise.var"#17#25"{typeof(loss),Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,2,Nothing}}}) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface2.jl:0
 [31] pullback(::Function, ::Zygote.Params) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface.jl:172
 [32] gradient(::Function, ::Zygote.Params) at C:\Users\ilanc\.julia\packages\Zygote\1GXzF\src\compiler\interface.jl:53
 [33] macro expansion at C:\Users\ilanc\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:88 [inlined]
 [34] macro expansion at C:\Users\ilanc\.julia\packages\Juno\tLMZd\src\progress.jl:134 [inlined]
 [35] train!(::typeof(loss), ::Zygote.Params, ::Array{Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,2,Nothing}},1}, ::ADAM; cb::Flux.var"#throttled#20"{Flux.var"#throttled#16#21"{Bool,Bool,typeof(evalcb),Int64}}) at C:\Users\ilanc\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:81
 [36] top-level scope at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\examples\gcn.jl:44
 [37] include(::String) at .\client.jl:439
 [38] top-level scope at REPL[2]:1
in expression starting at C:\Users\ilanc\Dropbox\Stage-MTL\julia\GeometricFlux.jl\examples\gcn.jl:43
```

This error should be fixed by #62.

**Comment by avik-pal** [comment]
The PR does solve the GPU error. But the error on CPU error still persists.

**Comment by avik-pal** [comment]
Additionally, I seem to get a warning for scalar indexing on GPUs which is making the training really slow. Is this a know issue (or should I open one for it)?

**Comment by ilancoulon** [comment]
I'll check the error on the CPU.

I think you can open an issue for the GPU warning!

**Comment by ilancoulon** [comment]
I can't manage to reproduce your error. 
Can you explain to me how exactly you get this error please?

**Comment by avik-pal** [comment]
I removed the `|> gpu` from lines 22, 23, 25 and 31

**Comment by ilancoulon** [comment]
Hum, that's exactly what I did and I don't have any error...
Nevertheless, I tried adding a commit on #62, could you try again?

**Comment by avik-pal** [comment]
@ilancoulon Thank you, it seems fixed now.
